version: 2

models:

  - name: int_orders
    columns:
      - name: amount
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0.0
                inclusive: true

  - name: int_customers

  - name: int_products
    columns:
      - name: price
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0.0
                inclusive: true
