version: 2

models:
  - name: daily_sales
    columns:
      - name: order_date
        tests:
          - not_null
          - unique
        description: "The date of the order"

  - name: top_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
        description: "The unique identifier for each customer"
      - name: total_spent
        tests:
          - not_null
        description: "The total amount spent by the customer"

  - name: revenue_by_category
    columns:
      - name: category
        tests:
          - not_null
          - unique
        description: "The category of the product"
      
  - name: orders_by_country
    columns:
      - name: country
        tests:
          - not_null
          - unique
        description: "The country of the order"