version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
        description: "The unique identifier for each order"

      - name: amount
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0.0
                inclusive: true
        description: "The amount of the order"

      - name: customer_id
        tests:
          - not_null
        description: "The unique identifier for each customer"
      - name: product_id
        tests:
          - not_null
        description: "The unique identifier for each product"
      - name: order_date
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
        description: "The date of the order"

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
        description: "The unique identifier for each product"

      - name: price
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0.0
                inclusive: true
        description: "The price of the product"


