version: 2

sources:
  - name: retailpulse_silver
    catalog: workspace
    schema: retailpulse_silver
    tables:
      - name: orders
        description: "The orders table"
      - name: customers
        description: "The customers table"
      - name: products
        description: "The products table"
